"""add enums"""

from alembic import op
import sqlalchemy as sa



revision = '40132aad1e8a'
down_revision = 'e025509e2ca1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inventory_direction_enum = sa.Enum('in', 'out', name='inventory_direction')
    meal_issue_status_enum = sa.Enum('issued', 'confirmed', name='meal_issue_status')
    payment_type_enum = sa.Enum('one_time', 'subscription', name='payment_type')
    payment_status_enum = sa.Enum('pending', 'paid', 'failed', 'refunded', name='payment_status')
    purchase_request_status_enum = sa.Enum('pending', 'approved', 'rejected', name='purchase_request_status')

    inventory_direction_enum.create(bind, checkfirst=True)
    meal_issue_status_enum.create(bind, checkfirst=True)
    payment_type_enum.create(bind, checkfirst=True)
    payment_status_enum.create(bind, checkfirst=True)
    purchase_request_status_enum.create(bind, checkfirst=True)

    op.alter_column('inventory_transactions', 'direction',
               existing_type=sa.VARCHAR(length=10),
               type_=inventory_direction_enum,
               existing_nullable=False,
               postgresql_using='direction::inventory_direction')
    op.alter_column('meal_issues', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=meal_issue_status_enum,
               existing_nullable=False,
               postgresql_using='status::meal_issue_status')
    op.alter_column('payments', 'payment_type',
               existing_type=sa.VARCHAR(length=20),
               type_=payment_type_enum,
               existing_nullable=False,
               postgresql_using='payment_type::payment_type')
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=payment_status_enum,
               existing_nullable=False,
               postgresql_using='status::payment_status')
    op.alter_column('purchase_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=purchase_request_status_enum,
               existing_nullable=False,
               postgresql_using='status::purchase_request_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_requests', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='purchase_request_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               postgresql_using='status::text')
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('pending', 'paid', 'failed', 'refunded', name='payment_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               postgresql_using='status::text')
    op.alter_column('payments', 'payment_type',
               existing_type=sa.Enum('one_time', 'subscription', name='payment_type'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               postgresql_using='payment_type::text')
    op.alter_column('meal_issues', 'status',
               existing_type=sa.Enum('issued', 'confirmed', name='meal_issue_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               postgresql_using='status::text')
    op.alter_column('inventory_transactions', 'direction',
               existing_type=sa.Enum('in', 'out', name='inventory_direction'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               postgresql_using='direction::text')

    bind = op.get_bind()
    sa.Enum('pending', 'approved', 'rejected', name='purchase_request_status').drop(
        bind, checkfirst=True
    )
    sa.Enum('pending', 'paid', 'failed', 'refunded', name='payment_status').drop(
        bind, checkfirst=True
    )
    sa.Enum('one_time', 'subscription', name='payment_type').drop(bind, checkfirst=True)
    sa.Enum('issued', 'confirmed', name='meal_issue_status').drop(bind, checkfirst=True)
    sa.Enum('in', 'out', name='inventory_direction').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
